[tools]
golang = "1.25.4"
nodejs = "22.10.0"
yarn = "1.22.10"
bun = "1.0.26"
lua = "5.4.6"
k6 = "0.49.0"
terraform = "1.9.6"
terragrunt = "0.68.4"
trivy = "0.54.1"
tflint = "0.53.0"
terraform-docs = "0.18.0"
opentofu = "1.8.0"
helm = "3.14.1"
kubectl = "1.31"
erlang = "27.2.2"
elixir = "1.18.3-otp-27"
redis = "6.2.14"
remotectl = "latest"
